### PR TITLE
New pld-grid-search --persist-best flag persists the best model

### PR DESCRIPTION
**Pull request by dnouri**

### CODE REVIEW

**Comment by dnouri** [comment]
@benjamin-work Just checking: You saw that this will always save `cv_results` to the model metadata if it exists, right?

**Comment by benjamin-work** [comment]
But this is good, is it not?

**Comment by dnouri** [comment]
@benjamin-work Heh yeah this wasn't meant to be a trick question but rather making sure you noticed the feature. :-)

**Comment by benjamin-work** [comment]
na dann ;)

Maybe it's worth mentioning that the grid scores table can become quite large quickly. Is it maybe worth it to allow the user to drop some columns from the table?

**Comment by dnouri** [comment]
@benjamin-work 

> Maybe it's worth mentioning that the grid scores table can become quite large quickly. Is it maybe worth it to allow the user to drop some columns from the table?

You could in theory do this by adding one of those decorators and drop the columns you're not interested in from the json string. Not wonderfully easy, but maybe adequate.

A related thing is I tried to have [`to_json`](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.to_json.html) not save the index (I don't care about it), but there doesn't seem to be a `to_json(orient='list')` which exists for other formats.  So now those extra indexes wasting space are there and they don't really add to the ease of use (think processing the json on the client).  Do you think there's a more convenient format?

Examples of two formats:

```python
>>> pandas.DataFrame(cv_results).to_json(orient='columns')  # what's in there right now

{'mean_fit_time': {'0': 0.0025140444, '1': 0.002566576, '2': 0.0017402967},
 'mean_score_time': {'0': 0.0005291303, '1': 0.000506719, '2': 0.0003481706},
 'mean_test_score': {'0': 0.84, '1': 0.91, '2': 0.95},
 'mean_train_score': {'0': 0.8356205398, '1': 0.9249735485, '2': 0.9548310484},
 'param_C': {'0': 0.1, '1': 0.3, '2': 1.0},
 'params': {'0': {'C': 0.1}, '1': {'C': 0.3}, '2': {'C': 1.0}},
 'rank_test_score': {'0': 3, '1': 2, '2': 1},
 'split0_test_score': {'0': 0.9142857143, '1': 0.9714285714, '2': 1.0},
 'split0_train_score': {'0': 0.8769230769,
                        '1': 0.9230769231,
                        '2': 0.9384615385},
 'split1_test_score': {'0': 0.7575757576, '1': 0.8484848485, '2': 0.8787878788},
 'split1_train_score': {'0': 0.8358208955,
                        '1': 0.9253731343,
                        '2': 0.9701492537},
 'split2_test_score': {'0': 0.84375, '1': 0.90625, '2': 0.96875},
 'split2_train_score': {'0': 0.7941176471,
                        '1': 0.9264705882,
                        '2': 0.9558823529},
 'std_fit_time': {'0': 0.000381438, '1': 0.0001488138, '2': 0.0005736085},
 'std_score_time': {'0': 0.0001036609, '1': 6.17642e-05, '2': 2.15558e-05},
 'std_test_score': {'0': 0.0646364291, '1': 0.0507343263, '2': 0.0515847346},
 'std_train_score': {'0': 0.033805472, '1': 0.001413976, '2': 0.012957797}}
```

```python
>>> pandas.DataFrame(cv_results).to_json(orient='records')

[{'mean_fit_time': 0.0025140444,
  'mean_score_time': 0.0005291303,
  'mean_test_score': 0.84,
  'mean_train_score': 0.8356205398,
  'param_C': 0.1,
  'params': {'C': 0.1},
  'rank_test_score': 3,
  'split0_test_score': 0.9142857143,
  'split0_train_score': 0.8769230769,
  'split1_test_score': 0.7575757576,
  'split1_train_score': 0.8358208955,
  'split2_test_score': 0.84375,
  'split2_train_score': 0.7941176471,
  'std_fit_time': 0.000381438,
  'std_score_time': 0.0001036609,
  'std_test_score': 0.0646364291,
  'std_train_score': 0.033805472},
 {'mean_fit_time': 0.002566576,
  'mean_score_time': 0.000506719,
  'mean_test_score': 0.91,
  'mean_train_score': 0.9249735485,
  'param_C': 0.3,
  'params': {'C': 0.3},
  'rank_test_score': 2,
  'split0_test_score': 0.9714285714,
  'split0_train_score': 0.9230769231,
  'split1_test_score': 0.8484848485,
  'split1_train_score': 0.9253731343,
  'split2_test_score': 0.90625,
  'split2_train_score': 0.9264705882,
  'std_fit_time': 0.0001488138,
  'std_score_time': 6.17642e-05,
  'std_test_score': 0.0507343263,
  'std_train_score': 0.001413976},
 {'mean_fit_time': 0.0017402967,
  'mean_score_time': 0.0003481706,
  'mean_test_score': 0.95,
  'mean_train_score': 0.9548310484,
  'param_C': 1.0,
  'params': {'C': 1.0},
  'rank_test_score': 1,
  'split0_test_score': 1.0,
  'split0_train_score': 0.9384615385,
  'split1_test_score': 0.8787878788,
  'split1_train_score': 0.9701492537,
  'split2_test_score': 0.96875,
  'split2_train_score': 0.9558823529,
  'std_fit_time': 0.0005736085,
  'std_score_time': 2.15558e-05,
  'std_test_score': 0.0515847346,
  'std_train_score': 0.012957797}]
```

**Comment by benjamin-work** [comment]
> A related thing is I tried to have to_json not save the index (I don't care about it), but there doesn't seem to be a to_json(orient='list') which exists for other formats.

You could try to call `json.dumps(df.to_dict(orient='list'))` but I believe this can cause trouble (e.g. handling of NaNs).

Otherwise, despite being ugly, I would stick with the 'records' orientation, since it sticks most closely with the sklearn-internal representation of the grid scores.

**Comment by dnouri** [comment]
@benjamin-work Alright, changed it to use `orient='records'`.

Feel free to merge.

**Pull request merged**
